"""Third Migration

Revision ID: b9608c3e8f17
Revises: 0dcb13d15ea6
Create Date: 2019-05-02 14:46:34.219559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9608c3e8f17'
down_revision = '0dcb13d15ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
